Repository SR-16/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#3 Revert "Update Calculator"
  Calculator
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2 Create switchcase
  switchcase
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 Create Snake game
  Snake game
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#5 Create pinball
  pinball
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#6 Update README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022
